// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: pkg/pb/cogito.proto

package genproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_pkg_pb_cogito_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_cogito_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_cogito_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type Identifier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identifier) Reset() {
	*x = Identifier{}
	mi := &file_pkg_pb_cogito_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identifier) ProtoMessage() {}

func (x *Identifier) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_cogito_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identifier.ProtoReflect.Descriptor instead.
func (*Identifier) Descriptor() ([]byte, []int) {
	return file_pkg_pb_cogito_proto_rawDescGZIP(), []int{1}
}

func (x *Identifier) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Ids struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int32                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ids) Reset() {
	*x = Ids{}
	mi := &file_pkg_pb_cogito_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ids) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ids) ProtoMessage() {}

func (x *Ids) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_cogito_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ids.ProtoReflect.Descriptor instead.
func (*Ids) Descriptor() ([]byte, []int) {
	return file_pkg_pb_cogito_proto_rawDescGZIP(), []int{2}
}

func (x *Ids) GetIds() []int32 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type UserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRequest) Reset() {
	*x = UserRequest{}
	mi := &file_pkg_pb_cogito_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequest) ProtoMessage() {}

func (x *UserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_cogito_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequest.ProtoReflect.Descriptor instead.
func (*UserRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_cogito_proto_rawDescGZIP(), []int{3}
}

func (x *UserRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type User struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Username        string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Email           string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Bio             string                 `protobuf:"bytes,5,opt,name=bio,proto3" json:"bio,omitempty"`
	Posts           int32                  `protobuf:"varint,6,opt,name=posts,proto3" json:"posts,omitempty"`
	Likes           int32                  `protobuf:"varint,7,opt,name=likes,proto3" json:"likes,omitempty"`
	Following       int32                  `protobuf:"varint,8,opt,name=following,proto3" json:"following,omitempty"`
	Followers       int32                  `protobuf:"varint,9,opt,name=followers,proto3" json:"followers,omitempty"`
	Followed        bool                   `protobuf:"varint,10,opt,name=followed,proto3" json:"followed,omitempty"`
	Created         string                 `protobuf:"bytes,11,opt,name=created,proto3" json:"created,omitempty"`
	ProfilePhotoKey string                 `protobuf:"bytes,12,opt,name=profile_photo_key,json=profilePhotoKey,proto3" json:"profile_photo_key,omitempty"`
	CoverPhotoKey   string                 `protobuf:"bytes,13,opt,name=cover_photo_key,json=coverPhotoKey,proto3" json:"cover_photo_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_pkg_pb_cogito_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_cogito_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_pkg_pb_cogito_proto_rawDescGZIP(), []int{4}
}

func (x *User) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *User) GetPosts() int32 {
	if x != nil {
		return x.Posts
	}
	return 0
}

func (x *User) GetLikes() int32 {
	if x != nil {
		return x.Likes
	}
	return 0
}

func (x *User) GetFollowing() int32 {
	if x != nil {
		return x.Following
	}
	return 0
}

func (x *User) GetFollowers() int32 {
	if x != nil {
		return x.Followers
	}
	return 0
}

func (x *User) GetFollowed() bool {
	if x != nil {
		return x.Followed
	}
	return false
}

func (x *User) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *User) GetProfilePhotoKey() string {
	if x != nil {
		return x.ProfilePhotoKey
	}
	return ""
}

func (x *User) GetCoverPhotoKey() string {
	if x != nil {
		return x.CoverPhotoKey
	}
	return ""
}

type UpdateUserRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Username        *string                `protobuf:"bytes,2,opt,name=username,proto3,oneof" json:"username,omitempty"`
	Email           *string                `protobuf:"bytes,3,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Password        string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	OldPassword     string                 `protobuf:"bytes,5,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	Bio             *string                `protobuf:"bytes,6,opt,name=bio,proto3,oneof" json:"bio,omitempty"`
	ProfilePhotoKey *string                `protobuf:"bytes,7,opt,name=profile_photo_key,json=profilePhotoKey,proto3,oneof" json:"profile_photo_key,omitempty"`
	CoverPhotoKey   *string                `protobuf:"bytes,8,opt,name=cover_photo_key,json=coverPhotoKey,proto3,oneof" json:"cover_photo_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_pkg_pb_cogito_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_cogito_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_cogito_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateUserRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateUserRequest) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *UpdateUserRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *UpdateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UpdateUserRequest) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *UpdateUserRequest) GetBio() string {
	if x != nil && x.Bio != nil {
		return *x.Bio
	}
	return ""
}

func (x *UpdateUserRequest) GetProfilePhotoKey() string {
	if x != nil && x.ProfilePhotoKey != nil {
		return *x.ProfilePhotoKey
	}
	return ""
}

func (x *UpdateUserRequest) GetCoverPhotoKey() string {
	if x != nil && x.CoverPhotoKey != nil {
		return *x.CoverPhotoKey
	}
	return ""
}

type GetUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersRequest) Reset() {
	*x = GetUsersRequest{}
	mi := &file_pkg_pb_cogito_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersRequest) ProtoMessage() {}

func (x *GetUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_cogito_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersRequest.ProtoReflect.Descriptor instead.
func (*GetUsersRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_cogito_proto_rawDescGZIP(), []int{6}
}

func (x *GetUsersRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUsersRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *GetUsersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Users struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Users) Reset() {
	*x = Users{}
	mi := &file_pkg_pb_cogito_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Users) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Users) ProtoMessage() {}

func (x *Users) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_cogito_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Users.ProtoReflect.Descriptor instead.
func (*Users) Descriptor() ([]byte, []int) {
	return file_pkg_pb_cogito_proto_rawDescGZIP(), []int{7}
}

func (x *Users) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *Users) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type GetUserByUsernameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByUsernameRequest) Reset() {
	*x = GetUserByUsernameRequest{}
	mi := &file_pkg_pb_cogito_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByUsernameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByUsernameRequest) ProtoMessage() {}

func (x *GetUserByUsernameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_cogito_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByUsernameRequest.ProtoReflect.Descriptor instead.
func (*GetUserByUsernameRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_cogito_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserByUsernameRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type SearchUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUsersRequest) Reset() {
	*x = SearchUsersRequest{}
	mi := &file_pkg_pb_cogito_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUsersRequest) ProtoMessage() {}

func (x *SearchUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_cogito_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUsersRequest.ProtoReflect.Descriptor instead.
func (*SearchUsersRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_cogito_proto_rawDescGZIP(), []int{9}
}

func (x *SearchUsersRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchUsersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_pkg_pb_cogito_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_cogito_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pkg_pb_cogito_proto_rawDescGZIP(), []int{10}
}

type Credentials struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Credentials) Reset() {
	*x = Credentials{}
	mi := &file_pkg_pb_cogito_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Credentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credentials) ProtoMessage() {}

func (x *Credentials) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_cogito_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credentials.ProtoReflect.Descriptor instead.
func (*Credentials) Descriptor() ([]byte, []int) {
	return file_pkg_pb_cogito_proto_rawDescGZIP(), []int{11}
}

func (x *Credentials) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Credentials) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type SessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionRequest) Reset() {
	*x = SessionRequest{}
	mi := &file_pkg_pb_cogito_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionRequest) ProtoMessage() {}

func (x *SessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_cogito_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionRequest.ProtoReflect.Descriptor instead.
func (*SessionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_cogito_proto_rawDescGZIP(), []int{12}
}

func (x *SessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Created       string                 `protobuf:"bytes,3,opt,name=created,proto3" json:"created,omitempty"`
	Handle        string                 `protobuf:"bytes,4,opt,name=handle,proto3" json:"handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_pkg_pb_cogito_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_cogito_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_pkg_pb_cogito_proto_rawDescGZIP(), []int{13}
}

func (x *Session) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Session) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Session) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *Session) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

type Sessions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*Session             `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sessions) Reset() {
	*x = Sessions{}
	mi := &file_pkg_pb_cogito_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sessions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sessions) ProtoMessage() {}

func (x *Sessions) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_cogito_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sessions.ProtoReflect.Descriptor instead.
func (*Sessions) Descriptor() ([]byte, []int) {
	return file_pkg_pb_cogito_proto_rawDescGZIP(), []int{14}
}

func (x *Sessions) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type CreatePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	MediaKey      *string                `protobuf:"bytes,2,opt,name=media_key,json=mediaKey,proto3,oneof" json:"media_key,omitempty"`
	InReplyToId   *int32                 `protobuf:"varint,3,opt,name=in_reply_to_id,json=inReplyToId,proto3,oneof" json:"in_reply_to_id,omitempty"`
	QuoteOfId     *int32                 `protobuf:"varint,4,opt,name=quote_of_id,json=quoteOfId,proto3,oneof" json:"quote_of_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostRequest) Reset() {
	*x = CreatePostRequest{}
	mi := &file_pkg_pb_cogito_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostRequest) ProtoMessage() {}

func (x *CreatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_cogito_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostRequest.ProtoReflect.Descriptor instead.
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_cogito_proto_rawDescGZIP(), []int{15}
}

func (x *CreatePostRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreatePostRequest) GetMediaKey() string {
	if x != nil && x.MediaKey != nil {
		return *x.MediaKey
	}
	return ""
}

func (x *CreatePostRequest) GetInReplyToId() int32 {
	if x != nil && x.InReplyToId != nil {
		return *x.InReplyToId
	}
	return 0
}

func (x *CreatePostRequest) GetQuoteOfId() int32 {
	if x != nil && x.QuoteOfId != nil {
		return *x.QuoteOfId
	}
	return 0
}

type PostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int32                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostRequest) Reset() {
	*x = PostRequest{}
	mi := &file_pkg_pb_cogito_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostRequest) ProtoMessage() {}

func (x *PostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_cogito_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostRequest.ProtoReflect.Descriptor instead.
func (*PostRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_cogito_proto_rawDescGZIP(), []int{16}
}

func (x *PostRequest) GetPostId() int32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type Post struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Likes         int32                  `protobuf:"varint,4,opt,name=likes,proto3" json:"likes,omitempty"`
	Liked         bool                   `protobuf:"varint,5,opt,name=liked,proto3" json:"liked,omitempty"`
	Reposts       int32                  `protobuf:"varint,6,opt,name=reposts,proto3" json:"reposts,omitempty"`
	Reposted      bool                   `protobuf:"varint,7,opt,name=reposted,proto3" json:"reposted,omitempty"`
	Created       string                 `protobuf:"bytes,8,opt,name=created,proto3" json:"created,omitempty"`
	RepostOfId    *int32                 `protobuf:"varint,9,opt,name=repost_of_id,json=repostOfId,proto3,oneof" json:"repost_of_id,omitempty"`
	MediaKey      string                 `protobuf:"bytes,11,opt,name=media_key,json=mediaKey,proto3" json:"media_key,omitempty"`
	Replies       int32                  `protobuf:"varint,12,opt,name=replies,proto3" json:"replies,omitempty"`
	InReplyToId   int32                  `protobuf:"varint,13,opt,name=in_reply_to_id,json=inReplyToId,proto3" json:"in_reply_to_id,omitempty"`
	QuoteOfId     int32                  `protobuf:"varint,14,opt,name=quote_of_id,json=quoteOfId,proto3" json:"quote_of_id,omitempty"`
	QuotePost     *Post                  `protobuf:"bytes,15,opt,name=quote_post,json=quotePost,proto3" json:"quote_post,omitempty"`
	RepostOf      *Post                  `protobuf:"bytes,16,opt,name=repost_of,json=repostOf,proto3" json:"repost_of,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Post) Reset() {
	*x = Post{}
	mi := &file_pkg_pb_cogito_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Post) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post) ProtoMessage() {}

func (x *Post) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_cogito_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post.ProtoReflect.Descriptor instead.
func (*Post) Descriptor() ([]byte, []int) {
	return file_pkg_pb_cogito_proto_rawDescGZIP(), []int{17}
}

func (x *Post) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Post) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Post) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Post) GetLikes() int32 {
	if x != nil {
		return x.Likes
	}
	return 0
}

func (x *Post) GetLiked() bool {
	if x != nil {
		return x.Liked
	}
	return false
}

func (x *Post) GetReposts() int32 {
	if x != nil {
		return x.Reposts
	}
	return 0
}

func (x *Post) GetReposted() bool {
	if x != nil {
		return x.Reposted
	}
	return false
}

func (x *Post) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *Post) GetRepostOfId() int32 {
	if x != nil && x.RepostOfId != nil {
		return *x.RepostOfId
	}
	return 0
}

func (x *Post) GetMediaKey() string {
	if x != nil {
		return x.MediaKey
	}
	return ""
}

func (x *Post) GetReplies() int32 {
	if x != nil {
		return x.Replies
	}
	return 0
}

func (x *Post) GetInReplyToId() int32 {
	if x != nil {
		return x.InReplyToId
	}
	return 0
}

func (x *Post) GetQuoteOfId() int32 {
	if x != nil {
		return x.QuoteOfId
	}
	return 0
}

func (x *Post) GetQuotePost() *Post {
	if x != nil {
		return x.QuotePost
	}
	return nil
}

func (x *Post) GetRepostOf() *Post {
	if x != nil {
		return x.RepostOf
	}
	return nil
}

type GetFeedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        string                 `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedRequest) Reset() {
	*x = GetFeedRequest{}
	mi := &file_pkg_pb_cogito_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedRequest) ProtoMessage() {}

func (x *GetFeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_cogito_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedRequest.ProtoReflect.Descriptor instead.
func (*GetFeedRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_cogito_proto_rawDescGZIP(), []int{18}
}

func (x *GetFeedRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *GetFeedRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Posts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*Post                `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Posts) Reset() {
	*x = Posts{}
	mi := &file_pkg_pb_cogito_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Posts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Posts) ProtoMessage() {}

func (x *Posts) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_cogito_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Posts.ProtoReflect.Descriptor instead.
func (*Posts) Descriptor() ([]byte, []int) {
	return file_pkg_pb_cogito_proto_rawDescGZIP(), []int{19}
}

func (x *Posts) GetPosts() []*Post {
	if x != nil {
		return x.Posts
	}
	return nil
}

func (x *Posts) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type GetPostsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostsRequest) Reset() {
	*x = GetPostsRequest{}
	mi := &file_pkg_pb_cogito_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostsRequest) ProtoMessage() {}

func (x *GetPostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_cogito_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostsRequest.ProtoReflect.Descriptor instead.
func (*GetPostsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_cogito_proto_rawDescGZIP(), []int{20}
}

func (x *GetPostsRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetPostsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *GetPostsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetHashtagPostsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHashtagPostsRequest) Reset() {
	*x = GetHashtagPostsRequest{}
	mi := &file_pkg_pb_cogito_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHashtagPostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHashtagPostsRequest) ProtoMessage() {}

func (x *GetHashtagPostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_cogito_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHashtagPostsRequest.ProtoReflect.Descriptor instead.
func (*GetHashtagPostsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_cogito_proto_rawDescGZIP(), []int{21}
}

func (x *GetHashtagPostsRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *GetHashtagPostsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *GetHashtagPostsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetRepliesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int32                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRepliesRequest) Reset() {
	*x = GetRepliesRequest{}
	mi := &file_pkg_pb_cogito_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepliesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepliesRequest) ProtoMessage() {}

func (x *GetRepliesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_cogito_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepliesRequest.ProtoReflect.Descriptor instead.
func (*GetRepliesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_cogito_proto_rawDescGZIP(), []int{22}
}

func (x *GetRepliesRequest) GetPostId() int32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *GetRepliesRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *GetRepliesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Hashtag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PostCount     int32                  `protobuf:"varint,3,opt,name=post_count,json=postCount,proto3" json:"post_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hashtag) Reset() {
	*x = Hashtag{}
	mi := &file_pkg_pb_cogito_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hashtag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hashtag) ProtoMessage() {}

func (x *Hashtag) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_cogito_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hashtag.ProtoReflect.Descriptor instead.
func (*Hashtag) Descriptor() ([]byte, []int) {
	return file_pkg_pb_cogito_proto_rawDescGZIP(), []int{23}
}

func (x *Hashtag) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Hashtag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Hashtag) GetPostCount() int32 {
	if x != nil {
		return x.PostCount
	}
	return 0
}

type Hashtags struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hashtags      []*Hashtag             `protobuf:"bytes,1,rep,name=hashtags,proto3" json:"hashtags,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hashtags) Reset() {
	*x = Hashtags{}
	mi := &file_pkg_pb_cogito_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hashtags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hashtags) ProtoMessage() {}

func (x *Hashtags) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_cogito_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hashtags.ProtoReflect.Descriptor instead.
func (*Hashtags) Descriptor() ([]byte, []int) {
	return file_pkg_pb_cogito_proto_rawDescGZIP(), []int{24}
}

func (x *Hashtags) GetHashtags() []*Hashtag {
	if x != nil {
		return x.Hashtags
	}
	return nil
}

func (x *Hashtags) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type SearchHashtagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchHashtagsRequest) Reset() {
	*x = SearchHashtagsRequest{}
	mi := &file_pkg_pb_cogito_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchHashtagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchHashtagsRequest) ProtoMessage() {}

func (x *SearchHashtagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_cogito_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchHashtagsRequest.ProtoReflect.Descriptor instead.
func (*SearchHashtagsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_cogito_proto_rawDescGZIP(), []int{25}
}

func (x *SearchHashtagsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchHashtagsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type VerifyUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyUploadRequest) Reset() {
	*x = VerifyUploadRequest{}
	mi := &file_pkg_pb_cogito_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyUploadRequest) ProtoMessage() {}

func (x *VerifyUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_cogito_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyUploadRequest.ProtoReflect.Descriptor instead.
func (*VerifyUploadRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_cogito_proto_rawDescGZIP(), []int{26}
}

func (x *VerifyUploadRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *VerifyUploadRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ConsumeUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeUploadRequest) Reset() {
	*x = ConsumeUploadRequest{}
	mi := &file_pkg_pb_cogito_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeUploadRequest) ProtoMessage() {}

func (x *ConsumeUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_cogito_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeUploadRequest.ProtoReflect.Descriptor instead.
func (*ConsumeUploadRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_cogito_proto_rawDescGZIP(), []int{27}
}

func (x *ConsumeUploadRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ConsumeUploadRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DeleteImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteImageRequest) Reset() {
	*x = DeleteImageRequest{}
	mi := &file_pkg_pb_cogito_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteImageRequest) ProtoMessage() {}

func (x *DeleteImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_cogito_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteImageRequest.ProtoReflect.Descriptor instead.
func (*DeleteImageRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_cogito_proto_rawDescGZIP(), []int{28}
}

func (x *DeleteImageRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_pkg_pb_cogito_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_cogito_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_cogito_proto_rawDescGZIP(), []int{29}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *SearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetNotificationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationsRequest) Reset() {
	*x = GetNotificationsRequest{}
	mi := &file_pkg_pb_cogito_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationsRequest) ProtoMessage() {}

func (x *GetNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_cogito_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationsRequest.ProtoReflect.Descriptor instead.
func (*GetNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_cogito_proto_rawDescGZIP(), []int{30}
}

func (x *GetNotificationsRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetNotificationsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *GetNotificationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ExternalId    int64                  `protobuf:"varint,2,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	UserId        int32                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ActorId       int32                  `protobuf:"varint,4,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	EntityId      string                 `protobuf:"bytes,6,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Read          bool                   `protobuf:"varint,7,opt,name=read,proto3" json:"read,omitempty"`
	Created       string                 `protobuf:"bytes,8,opt,name=created,proto3" json:"created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_pkg_pb_cogito_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_cogito_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_pkg_pb_cogito_proto_rawDescGZIP(), []int{31}
}

func (x *Notification) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Notification) GetExternalId() int64 {
	if x != nil {
		return x.ExternalId
	}
	return 0
}

func (x *Notification) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Notification) GetActorId() int32 {
	if x != nil {
		return x.ActorId
	}
	return 0
}

func (x *Notification) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Notification) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *Notification) GetRead() bool {
	if x != nil {
		return x.Read
	}
	return false
}

func (x *Notification) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

type Notifications struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notifications []*Notification        `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notifications) Reset() {
	*x = Notifications{}
	mi := &file_pkg_pb_cogito_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notifications) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notifications) ProtoMessage() {}

func (x *Notifications) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_cogito_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notifications.ProtoReflect.Descriptor instead.
func (*Notifications) Descriptor() ([]byte, []int) {
	return file_pkg_pb_cogito_proto_rawDescGZIP(), []int{32}
}

func (x *Notifications) GetNotifications() []*Notification {
	if x != nil {
		return x.Notifications
	}
	return nil
}

func (x *Notifications) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type NotificationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId int64                  `protobuf:"varint,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	UserId         int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NotificationRequest) Reset() {
	*x = NotificationRequest{}
	mi := &file_pkg_pb_cogito_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationRequest) ProtoMessage() {}

func (x *NotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_cogito_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationRequest.ProtoReflect.Descriptor instead.
func (*NotificationRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_cogito_proto_rawDescGZIP(), []int{33}
}

func (x *NotificationRequest) GetNotificationId() int64 {
	if x != nil {
		return x.NotificationId
	}
	return 0
}

func (x *NotificationRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UnreadCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnreadCountResponse) Reset() {
	*x = UnreadCountResponse{}
	mi := &file_pkg_pb_cogito_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnreadCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnreadCountResponse) ProtoMessage() {}

func (x *UnreadCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_cogito_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnreadCountResponse.ProtoReflect.Descriptor instead.
func (*UnreadCountResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_cogito_proto_rawDescGZIP(), []int{34}
}

func (x *UnreadCountResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_pkg_pb_cogito_proto protoreflect.FileDescriptor

const file_pkg_pb_cogito_proto_rawDesc = "" +
	"\n" +
	"\x13pkg/pb/cogito.proto\x12\x06cogito\"u\n" +
	"\x11CreateUserRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\"\x1c\n" +
	"\n" +
	"Identifier\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x17\n" +
	"\x03Ids\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x05R\x03ids\"&\n" +
	"\vUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\"\xe0\x02\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x10\n" +
	"\x03bio\x18\x05 \x01(\tR\x03bio\x12\x14\n" +
	"\x05posts\x18\x06 \x01(\x05R\x05posts\x12\x14\n" +
	"\x05likes\x18\a \x01(\x05R\x05likes\x12\x1c\n" +
	"\tfollowing\x18\b \x01(\x05R\tfollowing\x12\x1c\n" +
	"\tfollowers\x18\t \x01(\x05R\tfollowers\x12\x1a\n" +
	"\bfollowed\x18\n" +
	" \x01(\bR\bfollowed\x12\x18\n" +
	"\acreated\x18\v \x01(\tR\acreated\x12*\n" +
	"\x11profile_photo_key\x18\f \x01(\tR\x0fprofilePhotoKey\x12&\n" +
	"\x0fcover_photo_key\x18\r \x01(\tR\rcoverPhotoKey\"\xee\x02\n" +
	"\x11UpdateUserRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1f\n" +
	"\busername\x18\x02 \x01(\tH\x01R\busername\x88\x01\x01\x12\x19\n" +
	"\x05email\x18\x03 \x01(\tH\x02R\x05email\x88\x01\x01\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12!\n" +
	"\fold_password\x18\x05 \x01(\tR\voldPassword\x12\x15\n" +
	"\x03bio\x18\x06 \x01(\tH\x03R\x03bio\x88\x01\x01\x12/\n" +
	"\x11profile_photo_key\x18\a \x01(\tH\x04R\x0fprofilePhotoKey\x88\x01\x01\x12+\n" +
	"\x0fcover_photo_key\x18\b \x01(\tH\x05R\rcoverPhotoKey\x88\x01\x01B\a\n" +
	"\x05_nameB\v\n" +
	"\t_usernameB\b\n" +
	"\x06_emailB\x06\n" +
	"\x04_bioB\x14\n" +
	"\x12_profile_photo_keyB\x12\n" +
	"\x10_cover_photo_key\"X\n" +
	"\x0fGetUsersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"L\n" +
	"\x05Users\x12\"\n" +
	"\x05users\x18\x01 \x03(\v2\f.cogito.UserR\x05users\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"6\n" +
	"\x18GetUserByUsernameRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"@\n" +
	"\x12SearchUsersRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\a\n" +
	"\x05Empty\"?\n" +
	"\vCredentials\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"/\n" +
	"\x0eSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"d\n" +
	"\aSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x18\n" +
	"\acreated\x18\x03 \x01(\tR\acreated\x12\x16\n" +
	"\x06handle\x18\x04 \x01(\tR\x06handle\"7\n" +
	"\bSessions\x12+\n" +
	"\bsessions\x18\x01 \x03(\v2\x0f.cogito.SessionR\bsessions\"\xcf\x01\n" +
	"\x11CreatePostRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12 \n" +
	"\tmedia_key\x18\x02 \x01(\tH\x00R\bmediaKey\x88\x01\x01\x12(\n" +
	"\x0ein_reply_to_id\x18\x03 \x01(\x05H\x01R\vinReplyToId\x88\x01\x01\x12#\n" +
	"\vquote_of_id\x18\x04 \x01(\x05H\x02R\tquoteOfId\x88\x01\x01B\f\n" +
	"\n" +
	"_media_keyB\x11\n" +
	"\x0f_in_reply_to_idB\x0e\n" +
	"\f_quote_of_id\"&\n" +
	"\vPostRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x05R\x06postId\"\xd7\x03\n" +
	"\x04Post\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x14\n" +
	"\x05likes\x18\x04 \x01(\x05R\x05likes\x12\x14\n" +
	"\x05liked\x18\x05 \x01(\bR\x05liked\x12\x18\n" +
	"\areposts\x18\x06 \x01(\x05R\areposts\x12\x1a\n" +
	"\breposted\x18\a \x01(\bR\breposted\x12\x18\n" +
	"\acreated\x18\b \x01(\tR\acreated\x12%\n" +
	"\frepost_of_id\x18\t \x01(\x05H\x00R\n" +
	"repostOfId\x88\x01\x01\x12\x1b\n" +
	"\tmedia_key\x18\v \x01(\tR\bmediaKey\x12\x18\n" +
	"\areplies\x18\f \x01(\x05R\areplies\x12#\n" +
	"\x0ein_reply_to_id\x18\r \x01(\x05R\vinReplyToId\x12\x1e\n" +
	"\vquote_of_id\x18\x0e \x01(\x05R\tquoteOfId\x12+\n" +
	"\n" +
	"quote_post\x18\x0f \x01(\v2\f.cogito.PostR\tquotePost\x12)\n" +
	"\trepost_of\x18\x10 \x01(\v2\f.cogito.PostR\brepostOfB\x0f\n" +
	"\r_repost_of_idJ\x04\b\n" +
	"\x10\v\">\n" +
	"\x0eGetFeedRequest\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"L\n" +
	"\x05Posts\x12\"\n" +
	"\x05posts\x18\x01 \x03(\v2\f.cogito.PostR\x05posts\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"X\n" +
	"\x0fGetPostsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"X\n" +
	"\x16GetHashtagPostsRequest\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"Z\n" +
	"\x11GetRepliesRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x05R\x06postId\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"L\n" +
	"\aHashtag\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"post_count\x18\x03 \x01(\x05R\tpostCount\"X\n" +
	"\bHashtags\x12+\n" +
	"\bhashtags\x18\x01 \x03(\v2\x0f.cogito.HashtagR\bhashtags\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"C\n" +
	"\x15SearchHashtagsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"J\n" +
	"\x13VerifyUploadRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\"K\n" +
	"\x14ConsumeUploadRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\"0\n" +
	"\x12DeleteImageRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\"S\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"`\n" +
	"\x17GetNotificationsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\xd2\x01\n" +
	"\fNotification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vexternal_id\x18\x02 \x01(\x03R\n" +
	"externalId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x05R\x06userId\x12\x19\n" +
	"\bactor_id\x18\x04 \x01(\x05R\aactorId\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x1b\n" +
	"\tentity_id\x18\x06 \x01(\tR\bentityId\x12\x12\n" +
	"\x04read\x18\a \x01(\bR\x04read\x12\x18\n" +
	"\acreated\x18\b \x01(\tR\acreated\"l\n" +
	"\rNotifications\x12:\n" +
	"\rnotifications\x18\x01 \x03(\v2\x14.cogito.NotificationR\rnotifications\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"W\n" +
	"\x13NotificationRequest\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\x03R\x0enotificationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\"+\n" +
	"\x13UnreadCountResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count2\xb2\x04\n" +
	"\vUserService\x12;\n" +
	"\n" +
	"CreateUser\x12\x19.cogito.CreateUserRequest\x1a\x12.cogito.Identifier\x12,\n" +
	"\aGetUser\x12\x13.cogito.UserRequest\x1a\f.cogito.User\x12C\n" +
	"\x11GetUserByUsername\x12 .cogito.GetUserByUsernameRequest\x1a\f.cogito.User\x12+\n" +
	"\rGetUsersByIds\x12\v.cogito.Ids\x1a\r.cogito.Users\x126\n" +
	"\n" +
	"UpdateUser\x12\x19.cogito.UpdateUserRequest\x1a\r.cogito.Empty\x126\n" +
	"\fGetFollowing\x12\x17.cogito.GetUsersRequest\x1a\r.cogito.Users\x126\n" +
	"\fGetFollowers\x12\x17.cogito.GetUsersRequest\x1a\r.cogito.Users\x120\n" +
	"\n" +
	"FollowUser\x12\x13.cogito.UserRequest\x1a\r.cogito.Empty\x122\n" +
	"\fUnfollowUser\x12\x13.cogito.UserRequest\x1a\r.cogito.Empty\x128\n" +
	"\vSearchUsers\x12\x1a.cogito.SearchUsersRequest\x1a\r.cogito.Users2\xe9\x01\n" +
	"\vAuthService\x125\n" +
	"\rCreateSession\x12\x13.cogito.Credentials\x1a\x0f.cogito.Session\x125\n" +
	"\n" +
	"GetSession\x12\x16.cogito.SessionRequest\x1a\x0f.cogito.Session\x126\n" +
	"\rDeleteSession\x12\x16.cogito.SessionRequest\x1a\r.cogito.Empty\x124\n" +
	"\vGetSessions\x12\x13.cogito.UserRequest\x1a\x10.cogito.Sessions2\xfb\x05\n" +
	"\vPostService\x12;\n" +
	"\n" +
	"CreatePost\x12\x19.cogito.CreatePostRequest\x1a\x12.cogito.Identifier\x120\n" +
	"\aGetFeed\x12\x16.cogito.GetFeedRequest\x1a\r.cogito.Posts\x122\n" +
	"\bGetPosts\x12\x17.cogito.GetPostsRequest\x1a\r.cogito.Posts\x127\n" +
	"\rGetLikedPosts\x12\x17.cogito.GetPostsRequest\x1a\r.cogito.Posts\x12@\n" +
	"\x0fGetHashtagPosts\x12\x1e.cogito.GetHashtagPostsRequest\x1a\r.cogito.Posts\x12,\n" +
	"\aGetPost\x12\x13.cogito.PostRequest\x1a\f.cogito.Post\x12+\n" +
	"\rGetPostsByIds\x12\v.cogito.Ids\x1a\r.cogito.Posts\x120\n" +
	"\n" +
	"DeletePost\x12\x13.cogito.PostRequest\x1a\r.cogito.Empty\x12.\n" +
	"\bLikePost\x12\x13.cogito.PostRequest\x1a\r.cogito.Empty\x120\n" +
	"\n" +
	"UnlikePost\x12\x13.cogito.PostRequest\x1a\r.cogito.Empty\x120\n" +
	"\n" +
	"RepostPost\x12\x13.cogito.PostRequest\x1a\r.cogito.Empty\x122\n" +
	"\fRemoveRepost\x12\x13.cogito.PostRequest\x1a\r.cogito.Empty\x126\n" +
	"\n" +
	"GetReplies\x12\x19.cogito.GetRepliesRequest\x1a\r.cogito.Posts\x12A\n" +
	"\x0eSearchHashtags\x12\x1d.cogito.SearchHashtagsRequest\x1a\x10.cogito.Hashtags2\xc2\x01\n" +
	"\fImageService\x12:\n" +
	"\fVerifyUpload\x12\x1b.cogito.VerifyUploadRequest\x1a\r.cogito.Empty\x12<\n" +
	"\rConsumeUpload\x12\x1c.cogito.ConsumeUploadRequest\x1a\r.cogito.Empty\x128\n" +
	"\vDeleteImage\x12\x1a.cogito.DeleteImageRequest\x1a\r.cogito.Empty2\xb4\x01\n" +
	"\rSearchService\x123\n" +
	"\vSearchUsers\x12\x15.cogito.SearchRequest\x1a\r.cogito.Users\x123\n" +
	"\vSearchPosts\x12\x15.cogito.SearchRequest\x1a\r.cogito.Posts\x129\n" +
	"\x0eSearchHashtags\x12\x15.cogito.SearchRequest\x1a\x10.cogito.Hashtags2\xe9\x01\n" +
	"\x13NotificationService\x12J\n" +
	"\x10GetNotifications\x12\x1f.cogito.GetNotificationsRequest\x1a\x15.cogito.Notifications\x12B\n" +
	"\x14MarkNotificationRead\x12\x1b.cogito.NotificationRequest\x1a\r.cogito.Empty\x12B\n" +
	"\x0eGetUnreadCount\x12\x13.cogito.UserRequest\x1a\x1b.cogito.UnreadCountResponseB\fZ\n" +
	"./genprotob\x06proto3"

var (
	file_pkg_pb_cogito_proto_rawDescOnce sync.Once
	file_pkg_pb_cogito_proto_rawDescData []byte
)

func file_pkg_pb_cogito_proto_rawDescGZIP() []byte {
	file_pkg_pb_cogito_proto_rawDescOnce.Do(func() {
		file_pkg_pb_cogito_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_pb_cogito_proto_rawDesc), len(file_pkg_pb_cogito_proto_rawDesc)))
	})
	return file_pkg_pb_cogito_proto_rawDescData
}

var file_pkg_pb_cogito_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_pkg_pb_cogito_proto_goTypes = []any{
	(*CreateUserRequest)(nil),        // 0: cogito.CreateUserRequest
	(*Identifier)(nil),               // 1: cogito.Identifier
	(*Ids)(nil),                      // 2: cogito.Ids
	(*UserRequest)(nil),              // 3: cogito.UserRequest
	(*User)(nil),                     // 4: cogito.User
	(*UpdateUserRequest)(nil),        // 5: cogito.UpdateUserRequest
	(*GetUsersRequest)(nil),          // 6: cogito.GetUsersRequest
	(*Users)(nil),                    // 7: cogito.Users
	(*GetUserByUsernameRequest)(nil), // 8: cogito.GetUserByUsernameRequest
	(*SearchUsersRequest)(nil),       // 9: cogito.SearchUsersRequest
	(*Empty)(nil),                    // 10: cogito.Empty
	(*Credentials)(nil),              // 11: cogito.Credentials
	(*SessionRequest)(nil),           // 12: cogito.SessionRequest
	(*Session)(nil),                  // 13: cogito.Session
	(*Sessions)(nil),                 // 14: cogito.Sessions
	(*CreatePostRequest)(nil),        // 15: cogito.CreatePostRequest
	(*PostRequest)(nil),              // 16: cogito.PostRequest
	(*Post)(nil),                     // 17: cogito.Post
	(*GetFeedRequest)(nil),           // 18: cogito.GetFeedRequest
	(*Posts)(nil),                    // 19: cogito.Posts
	(*GetPostsRequest)(nil),          // 20: cogito.GetPostsRequest
	(*GetHashtagPostsRequest)(nil),   // 21: cogito.GetHashtagPostsRequest
	(*GetRepliesRequest)(nil),        // 22: cogito.GetRepliesRequest
	(*Hashtag)(nil),                  // 23: cogito.Hashtag
	(*Hashtags)(nil),                 // 24: cogito.Hashtags
	(*SearchHashtagsRequest)(nil),    // 25: cogito.SearchHashtagsRequest
	(*VerifyUploadRequest)(nil),      // 26: cogito.VerifyUploadRequest
	(*ConsumeUploadRequest)(nil),     // 27: cogito.ConsumeUploadRequest
	(*DeleteImageRequest)(nil),       // 28: cogito.DeleteImageRequest
	(*SearchRequest)(nil),            // 29: cogito.SearchRequest
	(*GetNotificationsRequest)(nil),  // 30: cogito.GetNotificationsRequest
	(*Notification)(nil),             // 31: cogito.Notification
	(*Notifications)(nil),            // 32: cogito.Notifications
	(*NotificationRequest)(nil),      // 33: cogito.NotificationRequest
	(*UnreadCountResponse)(nil),      // 34: cogito.UnreadCountResponse
}
var file_pkg_pb_cogito_proto_depIdxs = []int32{
	4,  // 0: cogito.Users.users:type_name -> cogito.User
	13, // 1: cogito.Sessions.sessions:type_name -> cogito.Session
	17, // 2: cogito.Post.quote_post:type_name -> cogito.Post
	17, // 3: cogito.Post.repost_of:type_name -> cogito.Post
	17, // 4: cogito.Posts.posts:type_name -> cogito.Post
	23, // 5: cogito.Hashtags.hashtags:type_name -> cogito.Hashtag
	31, // 6: cogito.Notifications.notifications:type_name -> cogito.Notification
	0,  // 7: cogito.UserService.CreateUser:input_type -> cogito.CreateUserRequest
	3,  // 8: cogito.UserService.GetUser:input_type -> cogito.UserRequest
	8,  // 9: cogito.UserService.GetUserByUsername:input_type -> cogito.GetUserByUsernameRequest
	2,  // 10: cogito.UserService.GetUsersByIds:input_type -> cogito.Ids
	5,  // 11: cogito.UserService.UpdateUser:input_type -> cogito.UpdateUserRequest
	6,  // 12: cogito.UserService.GetFollowing:input_type -> cogito.GetUsersRequest
	6,  // 13: cogito.UserService.GetFollowers:input_type -> cogito.GetUsersRequest
	3,  // 14: cogito.UserService.FollowUser:input_type -> cogito.UserRequest
	3,  // 15: cogito.UserService.UnfollowUser:input_type -> cogito.UserRequest
	9,  // 16: cogito.UserService.SearchUsers:input_type -> cogito.SearchUsersRequest
	11, // 17: cogito.AuthService.CreateSession:input_type -> cogito.Credentials
	12, // 18: cogito.AuthService.GetSession:input_type -> cogito.SessionRequest
	12, // 19: cogito.AuthService.DeleteSession:input_type -> cogito.SessionRequest
	3,  // 20: cogito.AuthService.GetSessions:input_type -> cogito.UserRequest
	15, // 21: cogito.PostService.CreatePost:input_type -> cogito.CreatePostRequest
	18, // 22: cogito.PostService.GetFeed:input_type -> cogito.GetFeedRequest
	20, // 23: cogito.PostService.GetPosts:input_type -> cogito.GetPostsRequest
	20, // 24: cogito.PostService.GetLikedPosts:input_type -> cogito.GetPostsRequest
	21, // 25: cogito.PostService.GetHashtagPosts:input_type -> cogito.GetHashtagPostsRequest
	16, // 26: cogito.PostService.GetPost:input_type -> cogito.PostRequest
	2,  // 27: cogito.PostService.GetPostsByIds:input_type -> cogito.Ids
	16, // 28: cogito.PostService.DeletePost:input_type -> cogito.PostRequest
	16, // 29: cogito.PostService.LikePost:input_type -> cogito.PostRequest
	16, // 30: cogito.PostService.UnlikePost:input_type -> cogito.PostRequest
	16, // 31: cogito.PostService.RepostPost:input_type -> cogito.PostRequest
	16, // 32: cogito.PostService.RemoveRepost:input_type -> cogito.PostRequest
	22, // 33: cogito.PostService.GetReplies:input_type -> cogito.GetRepliesRequest
	25, // 34: cogito.PostService.SearchHashtags:input_type -> cogito.SearchHashtagsRequest
	26, // 35: cogito.ImageService.VerifyUpload:input_type -> cogito.VerifyUploadRequest
	27, // 36: cogito.ImageService.ConsumeUpload:input_type -> cogito.ConsumeUploadRequest
	28, // 37: cogito.ImageService.DeleteImage:input_type -> cogito.DeleteImageRequest
	29, // 38: cogito.SearchService.SearchUsers:input_type -> cogito.SearchRequest
	29, // 39: cogito.SearchService.SearchPosts:input_type -> cogito.SearchRequest
	29, // 40: cogito.SearchService.SearchHashtags:input_type -> cogito.SearchRequest
	30, // 41: cogito.NotificationService.GetNotifications:input_type -> cogito.GetNotificationsRequest
	33, // 42: cogito.NotificationService.MarkNotificationRead:input_type -> cogito.NotificationRequest
	3,  // 43: cogito.NotificationService.GetUnreadCount:input_type -> cogito.UserRequest
	1,  // 44: cogito.UserService.CreateUser:output_type -> cogito.Identifier
	4,  // 45: cogito.UserService.GetUser:output_type -> cogito.User
	4,  // 46: cogito.UserService.GetUserByUsername:output_type -> cogito.User
	7,  // 47: cogito.UserService.GetUsersByIds:output_type -> cogito.Users
	10, // 48: cogito.UserService.UpdateUser:output_type -> cogito.Empty
	7,  // 49: cogito.UserService.GetFollowing:output_type -> cogito.Users
	7,  // 50: cogito.UserService.GetFollowers:output_type -> cogito.Users
	10, // 51: cogito.UserService.FollowUser:output_type -> cogito.Empty
	10, // 52: cogito.UserService.UnfollowUser:output_type -> cogito.Empty
	7,  // 53: cogito.UserService.SearchUsers:output_type -> cogito.Users
	13, // 54: cogito.AuthService.CreateSession:output_type -> cogito.Session
	13, // 55: cogito.AuthService.GetSession:output_type -> cogito.Session
	10, // 56: cogito.AuthService.DeleteSession:output_type -> cogito.Empty
	14, // 57: cogito.AuthService.GetSessions:output_type -> cogito.Sessions
	1,  // 58: cogito.PostService.CreatePost:output_type -> cogito.Identifier
	19, // 59: cogito.PostService.GetFeed:output_type -> cogito.Posts
	19, // 60: cogito.PostService.GetPosts:output_type -> cogito.Posts
	19, // 61: cogito.PostService.GetLikedPosts:output_type -> cogito.Posts
	19, // 62: cogito.PostService.GetHashtagPosts:output_type -> cogito.Posts
	17, // 63: cogito.PostService.GetPost:output_type -> cogito.Post
	19, // 64: cogito.PostService.GetPostsByIds:output_type -> cogito.Posts
	10, // 65: cogito.PostService.DeletePost:output_type -> cogito.Empty
	10, // 66: cogito.PostService.LikePost:output_type -> cogito.Empty
	10, // 67: cogito.PostService.UnlikePost:output_type -> cogito.Empty
	10, // 68: cogito.PostService.RepostPost:output_type -> cogito.Empty
	10, // 69: cogito.PostService.RemoveRepost:output_type -> cogito.Empty
	19, // 70: cogito.PostService.GetReplies:output_type -> cogito.Posts
	24, // 71: cogito.PostService.SearchHashtags:output_type -> cogito.Hashtags
	10, // 72: cogito.ImageService.VerifyUpload:output_type -> cogito.Empty
	10, // 73: cogito.ImageService.ConsumeUpload:output_type -> cogito.Empty
	10, // 74: cogito.ImageService.DeleteImage:output_type -> cogito.Empty
	7,  // 75: cogito.SearchService.SearchUsers:output_type -> cogito.Users
	19, // 76: cogito.SearchService.SearchPosts:output_type -> cogito.Posts
	24, // 77: cogito.SearchService.SearchHashtags:output_type -> cogito.Hashtags
	32, // 78: cogito.NotificationService.GetNotifications:output_type -> cogito.Notifications
	10, // 79: cogito.NotificationService.MarkNotificationRead:output_type -> cogito.Empty
	34, // 80: cogito.NotificationService.GetUnreadCount:output_type -> cogito.UnreadCountResponse
	44, // [44:81] is the sub-list for method output_type
	7,  // [7:44] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_pkg_pb_cogito_proto_init() }
func file_pkg_pb_cogito_proto_init() {
	if File_pkg_pb_cogito_proto != nil {
		return
	}
	file_pkg_pb_cogito_proto_msgTypes[5].OneofWrappers = []any{}
	file_pkg_pb_cogito_proto_msgTypes[15].OneofWrappers = []any{}
	file_pkg_pb_cogito_proto_msgTypes[17].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_pb_cogito_proto_rawDesc), len(file_pkg_pb_cogito_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   6,
		},
		GoTypes:           file_pkg_pb_cogito_proto_goTypes,
		DependencyIndexes: file_pkg_pb_cogito_proto_depIdxs,
		MessageInfos:      file_pkg_pb_cogito_proto_msgTypes,
	}.Build()
	File_pkg_pb_cogito_proto = out.File
	file_pkg_pb_cogito_proto_goTypes = nil
	file_pkg_pb_cogito_proto_depIdxs = nil
}
