apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cache
  labels:
    app: cogito
    component: cache
spec:
  serviceName: cache
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: cogito
      component: cache
  template:
    metadata:
      labels:
        app: cogito
        component: cache
    spec:
      serviceAccountName: cache
      automountServiceAccountToken: false
      containers:
      - name: cache
        image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.25.0
        args: ["--proactor_threads=1", "--maxmemory=300mb"]
        ports:
        - containerPort: 6379
          name: cache
        resources:
          limits:
            memory: 400Mi
          requests:
            memory: 300Mi
            cpu: 50m
        securityContext:
          allowPrivilegeEscalation: false
        volumeMounts:
        - name: cache-data
          mountPath: /data
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 5
          periodSeconds: 15
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 3
          periodSeconds: 10
  volumeClaimTemplates:
  - metadata:
      name: cache-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: cache
  labels:
    app: cogito
    component: cache
spec:
  selector:
    app: cogito
    component: cache
  ports:
  - name: cache
    port: 6379
    targetPort: cache
