apiVersion: apps/v1
kind: Deployment
metadata:
  name: imageservice
  labels:
    app: thoughts
    tier: backend
    component: imageservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thoughts
      tier: backend
      component: imageservice
  template:
    metadata:
      labels:
        app: thoughts
        tier: backend
        component: imageservice
    spec:
      containers:
      - name: imageservice
        image: localhost:5000/thoughts/imageservice
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5050
          name: grpc
        - containerPort: 8081
          name: http
        resources:
          limits:
            memory: 256Mi
          requests:
            memory: 64Mi
            cpu: 75m
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: thoughts-db-secret
              key: database-url
        - name: INTERNAL_GRPC_TOKEN
          valueFrom:
            secretKeyRef:
              name: thoughts-db-secret
              key: internal-grpc-token
        - name: IMAGE_DIR
          value: "/app/uploads"
        volumeMounts:
        - name: image-storage
          mountPath: /app/uploads
        livenessProbe:
          tcpSocket:
            port: 5050
          initialDelaySeconds: 10
          periodSeconds: 15
        readinessProbe:
          tcpSocket:
            port: 5050
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: image-storage
        persistentVolumeClaim:
          claimName: image-volume-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: imageservice
  labels:
    app: thoughts
    tier: backend
    component: imageservice
spec:
  type: ClusterIP
  selector:
    app: thoughts
    tier: backend
    component: imageservice
  ports:
  - name: grpc
    port: 5050
    targetPort: 5050
  - name: http
    port: 8081
    targetPort: 8081
