apiVersion: v1
kind: Service
metadata:
  name: searchservice
  labels:
    app: thoughts
    tier: backend
    component: searchservice
spec:
  selector:
    app: thoughts
    tier: backend
    component: searchservice
  ports:
  - port: 5050
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: searchservice
  labels:
    app: thoughts
    tier: backend
    component: searchservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: thoughts
      tier: backend
      component: searchservice
  template:
    metadata:
      labels:
        app: thoughts
        tier: backend
        component: searchservice
    spec:
      containers:
      - name: searchservice
        image: localhost:5000/thoughts/searchservice
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5050
        resources:
          limits:
            memory: 128Mi
          requests:
            memory: 64Mi
            cpu: 100m
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: thoughts-db-secret
              key: database-url
        - name: MEILI_HOST
          value: http://meilisearch:7700
        - name: MEILI_MASTER_KEY
          valueFrom:
            secretKeyRef:
              name: thoughts-db-secret
              key: meili-master-key
        - name: INTERNAL_GRPC_TOKEN
          valueFrom:
            secretKeyRef:
              name: thoughts-db-secret
              key: internal-grpc-token
        livenessProbe:
          tcpSocket:
            port: 5050
          initialDelaySeconds: 10
          periodSeconds: 15
        readinessProbe:
          tcpSocket:
            port: 5050
          initialDelaySeconds: 5
          periodSeconds: 10
