apiVersion: v1
kind: ServiceAccount
metadata:
  name: apigateway
  labels:
    app: cogito
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: authservice
  labels:
    app: cogito
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: userservice
  labels:
    app: cogito
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: imageservice
  labels:
    app: cogito
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flowservice
  labels:
    app: cogito
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postservice
  labels:
    app: cogito
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  labels:
    app: cogito
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: database
  labels:
    app: cogito
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cache
  labels:
    app: cogito
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: search
  labels:
    app: cogito
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: storage
  labels:
    app: cogito
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: broker
  labels:
    app: cogito
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: connect
  labels:
    app: cogito
automountServiceAccountToken: false
