// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: pb/thoughts.proto

package genproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_pb_thoughts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_thoughts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_pb_thoughts_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type Identifier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identifier) Reset() {
	*x = Identifier{}
	mi := &file_pb_thoughts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identifier) ProtoMessage() {}

func (x *Identifier) ProtoReflect() protoreflect.Message {
	mi := &file_pb_thoughts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identifier.ProtoReflect.Descriptor instead.
func (*Identifier) Descriptor() ([]byte, []int) {
	return file_pb_thoughts_proto_rawDescGZIP(), []int{1}
}

func (x *Identifier) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRequest) Reset() {
	*x = UserRequest{}
	mi := &file_pb_thoughts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequest) ProtoMessage() {}

func (x *UserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_thoughts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequest.ProtoReflect.Descriptor instead.
func (*UserRequest) Descriptor() ([]byte, []int) {
	return file_pb_thoughts_proto_rawDescGZIP(), []int{2}
}

func (x *UserRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Bio           string                 `protobuf:"bytes,5,opt,name=bio,proto3" json:"bio,omitempty"`
	Posts         int32                  `protobuf:"varint,6,opt,name=posts,proto3" json:"posts,omitempty"`
	Likes         int32                  `protobuf:"varint,7,opt,name=likes,proto3" json:"likes,omitempty"`
	Following     int32                  `protobuf:"varint,8,opt,name=following,proto3" json:"following,omitempty"`
	Followers     int32                  `protobuf:"varint,9,opt,name=followers,proto3" json:"followers,omitempty"`
	Followed      bool                   `protobuf:"varint,10,opt,name=followed,proto3" json:"followed,omitempty"`
	Created       string                 `protobuf:"bytes,11,opt,name=created,proto3" json:"created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_pb_thoughts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_pb_thoughts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_pb_thoughts_proto_rawDescGZIP(), []int{3}
}

func (x *User) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *User) GetPosts() int32 {
	if x != nil {
		return x.Posts
	}
	return 0
}

func (x *User) GetLikes() int32 {
	if x != nil {
		return x.Likes
	}
	return 0
}

func (x *User) GetFollowing() int32 {
	if x != nil {
		return x.Following
	}
	return 0
}

func (x *User) GetFollowers() int32 {
	if x != nil {
		return x.Followers
	}
	return 0
}

func (x *User) GetFollowed() bool {
	if x != nil {
		return x.Followed
	}
	return false
}

func (x *User) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	OldPassword   string                 `protobuf:"bytes,5,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	Bio           string                 `protobuf:"bytes,6,opt,name=bio,proto3" json:"bio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_pb_thoughts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_thoughts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_pb_thoughts_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpdateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UpdateUserRequest) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *UpdateUserRequest) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

type GetUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersRequest) Reset() {
	*x = GetUsersRequest{}
	mi := &file_pb_thoughts_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersRequest) ProtoMessage() {}

func (x *GetUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_thoughts_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersRequest.ProtoReflect.Descriptor instead.
func (*GetUsersRequest) Descriptor() ([]byte, []int) {
	return file_pb_thoughts_proto_rawDescGZIP(), []int{5}
}

func (x *GetUsersRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUsersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetUsersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Users struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Users) Reset() {
	*x = Users{}
	mi := &file_pb_thoughts_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Users) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Users) ProtoMessage() {}

func (x *Users) ProtoReflect() protoreflect.Message {
	mi := &file_pb_thoughts_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Users.ProtoReflect.Descriptor instead.
func (*Users) Descriptor() ([]byte, []int) {
	return file_pb_thoughts_proto_rawDescGZIP(), []int{6}
}

func (x *Users) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type GetUserByUsernameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByUsernameRequest) Reset() {
	*x = GetUserByUsernameRequest{}
	mi := &file_pb_thoughts_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByUsernameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByUsernameRequest) ProtoMessage() {}

func (x *GetUserByUsernameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_thoughts_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByUsernameRequest.ProtoReflect.Descriptor instead.
func (*GetUserByUsernameRequest) Descriptor() ([]byte, []int) {
	return file_pb_thoughts_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserByUsernameRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_pb_thoughts_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pb_thoughts_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pb_thoughts_proto_rawDescGZIP(), []int{8}
}

type Credentials struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Credentials) Reset() {
	*x = Credentials{}
	mi := &file_pb_thoughts_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Credentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credentials) ProtoMessage() {}

func (x *Credentials) ProtoReflect() protoreflect.Message {
	mi := &file_pb_thoughts_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credentials.ProtoReflect.Descriptor instead.
func (*Credentials) Descriptor() ([]byte, []int) {
	return file_pb_thoughts_proto_rawDescGZIP(), []int{9}
}

func (x *Credentials) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Credentials) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type SessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionRequest) Reset() {
	*x = SessionRequest{}
	mi := &file_pb_thoughts_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionRequest) ProtoMessage() {}

func (x *SessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_thoughts_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionRequest.ProtoReflect.Descriptor instead.
func (*SessionRequest) Descriptor() ([]byte, []int) {
	return file_pb_thoughts_proto_rawDescGZIP(), []int{10}
}

func (x *SessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Created       string                 `protobuf:"bytes,3,opt,name=created,proto3" json:"created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_pb_thoughts_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_pb_thoughts_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_pb_thoughts_proto_rawDescGZIP(), []int{11}
}

func (x *Session) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Session) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Session) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

type Sessions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*Session             `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sessions) Reset() {
	*x = Sessions{}
	mi := &file_pb_thoughts_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sessions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sessions) ProtoMessage() {}

func (x *Sessions) ProtoReflect() protoreflect.Message {
	mi := &file_pb_thoughts_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sessions.ProtoReflect.Descriptor instead.
func (*Sessions) Descriptor() ([]byte, []int) {
	return file_pb_thoughts_proto_rawDescGZIP(), []int{12}
}

func (x *Sessions) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type CreatePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostRequest) Reset() {
	*x = CreatePostRequest{}
	mi := &file_pb_thoughts_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostRequest) ProtoMessage() {}

func (x *CreatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_thoughts_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostRequest.ProtoReflect.Descriptor instead.
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return file_pb_thoughts_proto_rawDescGZIP(), []int{13}
}

func (x *CreatePostRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type PostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int32                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostRequest) Reset() {
	*x = PostRequest{}
	mi := &file_pb_thoughts_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostRequest) ProtoMessage() {}

func (x *PostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_thoughts_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostRequest.ProtoReflect.Descriptor instead.
func (*PostRequest) Descriptor() ([]byte, []int) {
	return file_pb_thoughts_proto_rawDescGZIP(), []int{14}
}

func (x *PostRequest) GetPostId() int32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type Post struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId            int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content           string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Likes             int32                  `protobuf:"varint,4,opt,name=likes,proto3" json:"likes,omitempty"`
	Liked             bool                   `protobuf:"varint,5,opt,name=liked,proto3" json:"liked,omitempty"`
	Reposts           int32                  `protobuf:"varint,6,opt,name=reposts,proto3" json:"reposts,omitempty"`
	Reposted          bool                   `protobuf:"varint,7,opt,name=reposted,proto3" json:"reposted,omitempty"`
	Created           string                 `protobuf:"bytes,8,opt,name=created,proto3" json:"created,omitempty"`
	RethoughtByUserId int32                  `protobuf:"varint,9,opt,name=rethought_by_user_id,json=rethoughtByUserId,proto3" json:"rethought_by_user_id,omitempty"`
	RethoughtCreated  string                 `protobuf:"bytes,10,opt,name=rethought_created,json=rethoughtCreated,proto3" json:"rethought_created,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Post) Reset() {
	*x = Post{}
	mi := &file_pb_thoughts_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Post) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post) ProtoMessage() {}

func (x *Post) ProtoReflect() protoreflect.Message {
	mi := &file_pb_thoughts_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post.ProtoReflect.Descriptor instead.
func (*Post) Descriptor() ([]byte, []int) {
	return file_pb_thoughts_proto_rawDescGZIP(), []int{15}
}

func (x *Post) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Post) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Post) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Post) GetLikes() int32 {
	if x != nil {
		return x.Likes
	}
	return 0
}

func (x *Post) GetLiked() bool {
	if x != nil {
		return x.Liked
	}
	return false
}

func (x *Post) GetReposts() int32 {
	if x != nil {
		return x.Reposts
	}
	return 0
}

func (x *Post) GetReposted() bool {
	if x != nil {
		return x.Reposted
	}
	return false
}

func (x *Post) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *Post) GetRethoughtByUserId() int32 {
	if x != nil {
		return x.RethoughtByUserId
	}
	return 0
}

func (x *Post) GetRethoughtCreated() string {
	if x != nil {
		return x.RethoughtCreated
	}
	return ""
}

type GetFeedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedRequest) Reset() {
	*x = GetFeedRequest{}
	mi := &file_pb_thoughts_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedRequest) ProtoMessage() {}

func (x *GetFeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_thoughts_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedRequest.ProtoReflect.Descriptor instead.
func (*GetFeedRequest) Descriptor() ([]byte, []int) {
	return file_pb_thoughts_proto_rawDescGZIP(), []int{16}
}

func (x *GetFeedRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetFeedRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Posts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*Post                `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Posts) Reset() {
	*x = Posts{}
	mi := &file_pb_thoughts_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Posts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Posts) ProtoMessage() {}

func (x *Posts) ProtoReflect() protoreflect.Message {
	mi := &file_pb_thoughts_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Posts.ProtoReflect.Descriptor instead.
func (*Posts) Descriptor() ([]byte, []int) {
	return file_pb_thoughts_proto_rawDescGZIP(), []int{17}
}

func (x *Posts) GetPosts() []*Post {
	if x != nil {
		return x.Posts
	}
	return nil
}

type GetPostsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostsRequest) Reset() {
	*x = GetPostsRequest{}
	mi := &file_pb_thoughts_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostsRequest) ProtoMessage() {}

func (x *GetPostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_thoughts_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostsRequest.ProtoReflect.Descriptor instead.
func (*GetPostsRequest) Descriptor() ([]byte, []int) {
	return file_pb_thoughts_proto_rawDescGZIP(), []int{18}
}

func (x *GetPostsRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetPostsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetPostsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_pb_thoughts_proto protoreflect.FileDescriptor

const file_pb_thoughts_proto_rawDesc = "" +
	"\n" +
	"\x11pb/thoughts.proto\x12\bthoughts\"u\n" +
	"\x11CreateUserRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\"\x1c\n" +
	"\n" +
	"Identifier\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"&\n" +
	"\vUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\"\x8c\x02\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x10\n" +
	"\x03bio\x18\x05 \x01(\tR\x03bio\x12\x14\n" +
	"\x05posts\x18\x06 \x01(\x05R\x05posts\x12\x14\n" +
	"\x05likes\x18\a \x01(\x05R\x05likes\x12\x1c\n" +
	"\tfollowing\x18\b \x01(\x05R\tfollowing\x12\x1c\n" +
	"\tfollowers\x18\t \x01(\x05R\tfollowers\x12\x1a\n" +
	"\bfollowed\x18\n" +
	" \x01(\bR\bfollowed\x12\x18\n" +
	"\acreated\x18\v \x01(\tR\acreated\"\xaa\x01\n" +
	"\x11UpdateUserRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12!\n" +
	"\fold_password\x18\x05 \x01(\tR\voldPassword\x12\x10\n" +
	"\x03bio\x18\x06 \x01(\tR\x03bio\"T\n" +
	"\x0fGetUsersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"-\n" +
	"\x05Users\x12$\n" +
	"\x05users\x18\x01 \x03(\v2\x0e.thoughts.UserR\x05users\"6\n" +
	"\x18GetUserByUsernameRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"\a\n" +
	"\x05Empty\"?\n" +
	"\vCredentials\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"/\n" +
	"\x0eSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"L\n" +
	"\aSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x18\n" +
	"\acreated\x18\x03 \x01(\tR\acreated\"9\n" +
	"\bSessions\x12-\n" +
	"\bsessions\x18\x01 \x03(\v2\x11.thoughts.SessionR\bsessions\"-\n" +
	"\x11CreatePostRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"&\n" +
	"\vPostRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x05R\x06postId\"\xa3\x02\n" +
	"\x04Post\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x14\n" +
	"\x05likes\x18\x04 \x01(\x05R\x05likes\x12\x14\n" +
	"\x05liked\x18\x05 \x01(\bR\x05liked\x12\x18\n" +
	"\areposts\x18\x06 \x01(\x05R\areposts\x12\x1a\n" +
	"\breposted\x18\a \x01(\bR\breposted\x12\x18\n" +
	"\acreated\x18\b \x01(\tR\acreated\x12/\n" +
	"\x14rethought_by_user_id\x18\t \x01(\x05R\x11rethoughtByUserId\x12+\n" +
	"\x11rethought_created\x18\n" +
	" \x01(\tR\x10rethoughtCreated\":\n" +
	"\x0eGetFeedRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"-\n" +
	"\x05Posts\x12$\n" +
	"\x05posts\x18\x01 \x03(\v2\x0e.thoughts.PostR\x05posts\"T\n" +
	"\x0fGetPostsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit2\xeb\x03\n" +
	"\vUserService\x12?\n" +
	"\n" +
	"CreateUser\x12\x1b.thoughts.CreateUserRequest\x1a\x14.thoughts.Identifier\x120\n" +
	"\aGetUser\x12\x15.thoughts.UserRequest\x1a\x0e.thoughts.User\x12G\n" +
	"\x11GetUserByUsername\x12\".thoughts.GetUserByUsernameRequest\x1a\x0e.thoughts.User\x12:\n" +
	"\n" +
	"UpdateUser\x12\x1b.thoughts.UpdateUserRequest\x1a\x0f.thoughts.Empty\x12:\n" +
	"\fGetFollowing\x12\x19.thoughts.GetUsersRequest\x1a\x0f.thoughts.Users\x12:\n" +
	"\fGetFollowers\x12\x19.thoughts.GetUsersRequest\x1a\x0f.thoughts.Users\x124\n" +
	"\n" +
	"FollowUser\x12\x15.thoughts.UserRequest\x1a\x0f.thoughts.Empty\x126\n" +
	"\fUnfollowUser\x12\x15.thoughts.UserRequest\x1a\x0f.thoughts.Empty2\xf9\x01\n" +
	"\vAuthService\x129\n" +
	"\rCreateSession\x12\x15.thoughts.Credentials\x1a\x11.thoughts.Session\x129\n" +
	"\n" +
	"GetSession\x12\x18.thoughts.SessionRequest\x1a\x11.thoughts.Session\x12:\n" +
	"\rDeleteSession\x12\x18.thoughts.SessionRequest\x1a\x0f.thoughts.Empty\x128\n" +
	"\vGetSessions\x12\x15.thoughts.UserRequest\x1a\x12.thoughts.Sessions2\xb9\x04\n" +
	"\vPostService\x12?\n" +
	"\n" +
	"CreatePost\x12\x1b.thoughts.CreatePostRequest\x1a\x14.thoughts.Identifier\x124\n" +
	"\aGetFeed\x12\x18.thoughts.GetFeedRequest\x1a\x0f.thoughts.Posts\x126\n" +
	"\bGetPosts\x12\x19.thoughts.GetPostsRequest\x1a\x0f.thoughts.Posts\x12;\n" +
	"\rGetLikedPosts\x12\x19.thoughts.GetPostsRequest\x1a\x0f.thoughts.Posts\x120\n" +
	"\aGetPost\x12\x15.thoughts.PostRequest\x1a\x0e.thoughts.Post\x124\n" +
	"\n" +
	"DeletePost\x12\x15.thoughts.PostRequest\x1a\x0f.thoughts.Empty\x122\n" +
	"\bLikePost\x12\x15.thoughts.PostRequest\x1a\x0f.thoughts.Empty\x124\n" +
	"\n" +
	"UnlikePost\x12\x15.thoughts.PostRequest\x1a\x0f.thoughts.Empty\x124\n" +
	"\n" +
	"RepostPost\x12\x15.thoughts.PostRequest\x1a\x0f.thoughts.Empty\x126\n" +
	"\fRemoveRepost\x12\x15.thoughts.PostRequest\x1a\x0f.thoughts.EmptyB\fZ\n" +
	"./genprotob\x06proto3"

var (
	file_pb_thoughts_proto_rawDescOnce sync.Once
	file_pb_thoughts_proto_rawDescData []byte
)

func file_pb_thoughts_proto_rawDescGZIP() []byte {
	file_pb_thoughts_proto_rawDescOnce.Do(func() {
		file_pb_thoughts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_thoughts_proto_rawDesc), len(file_pb_thoughts_proto_rawDesc)))
	})
	return file_pb_thoughts_proto_rawDescData
}

var file_pb_thoughts_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_pb_thoughts_proto_goTypes = []any{
	(*CreateUserRequest)(nil),        // 0: thoughts.CreateUserRequest
	(*Identifier)(nil),               // 1: thoughts.Identifier
	(*UserRequest)(nil),              // 2: thoughts.UserRequest
	(*User)(nil),                     // 3: thoughts.User
	(*UpdateUserRequest)(nil),        // 4: thoughts.UpdateUserRequest
	(*GetUsersRequest)(nil),          // 5: thoughts.GetUsersRequest
	(*Users)(nil),                    // 6: thoughts.Users
	(*GetUserByUsernameRequest)(nil), // 7: thoughts.GetUserByUsernameRequest
	(*Empty)(nil),                    // 8: thoughts.Empty
	(*Credentials)(nil),              // 9: thoughts.Credentials
	(*SessionRequest)(nil),           // 10: thoughts.SessionRequest
	(*Session)(nil),                  // 11: thoughts.Session
	(*Sessions)(nil),                 // 12: thoughts.Sessions
	(*CreatePostRequest)(nil),        // 13: thoughts.CreatePostRequest
	(*PostRequest)(nil),              // 14: thoughts.PostRequest
	(*Post)(nil),                     // 15: thoughts.Post
	(*GetFeedRequest)(nil),           // 16: thoughts.GetFeedRequest
	(*Posts)(nil),                    // 17: thoughts.Posts
	(*GetPostsRequest)(nil),          // 18: thoughts.GetPostsRequest
}
var file_pb_thoughts_proto_depIdxs = []int32{
	3,  // 0: thoughts.Users.users:type_name -> thoughts.User
	11, // 1: thoughts.Sessions.sessions:type_name -> thoughts.Session
	15, // 2: thoughts.Posts.posts:type_name -> thoughts.Post
	0,  // 3: thoughts.UserService.CreateUser:input_type -> thoughts.CreateUserRequest
	2,  // 4: thoughts.UserService.GetUser:input_type -> thoughts.UserRequest
	7,  // 5: thoughts.UserService.GetUserByUsername:input_type -> thoughts.GetUserByUsernameRequest
	4,  // 6: thoughts.UserService.UpdateUser:input_type -> thoughts.UpdateUserRequest
	5,  // 7: thoughts.UserService.GetFollowing:input_type -> thoughts.GetUsersRequest
	5,  // 8: thoughts.UserService.GetFollowers:input_type -> thoughts.GetUsersRequest
	2,  // 9: thoughts.UserService.FollowUser:input_type -> thoughts.UserRequest
	2,  // 10: thoughts.UserService.UnfollowUser:input_type -> thoughts.UserRequest
	9,  // 11: thoughts.AuthService.CreateSession:input_type -> thoughts.Credentials
	10, // 12: thoughts.AuthService.GetSession:input_type -> thoughts.SessionRequest
	10, // 13: thoughts.AuthService.DeleteSession:input_type -> thoughts.SessionRequest
	2,  // 14: thoughts.AuthService.GetSessions:input_type -> thoughts.UserRequest
	13, // 15: thoughts.PostService.CreatePost:input_type -> thoughts.CreatePostRequest
	16, // 16: thoughts.PostService.GetFeed:input_type -> thoughts.GetFeedRequest
	18, // 17: thoughts.PostService.GetPosts:input_type -> thoughts.GetPostsRequest
	18, // 18: thoughts.PostService.GetLikedPosts:input_type -> thoughts.GetPostsRequest
	14, // 19: thoughts.PostService.GetPost:input_type -> thoughts.PostRequest
	14, // 20: thoughts.PostService.DeletePost:input_type -> thoughts.PostRequest
	14, // 21: thoughts.PostService.LikePost:input_type -> thoughts.PostRequest
	14, // 22: thoughts.PostService.UnlikePost:input_type -> thoughts.PostRequest
	14, // 23: thoughts.PostService.RepostPost:input_type -> thoughts.PostRequest
	14, // 24: thoughts.PostService.RemoveRepost:input_type -> thoughts.PostRequest
	1,  // 25: thoughts.UserService.CreateUser:output_type -> thoughts.Identifier
	3,  // 26: thoughts.UserService.GetUser:output_type -> thoughts.User
	3,  // 27: thoughts.UserService.GetUserByUsername:output_type -> thoughts.User
	8,  // 28: thoughts.UserService.UpdateUser:output_type -> thoughts.Empty
	6,  // 29: thoughts.UserService.GetFollowing:output_type -> thoughts.Users
	6,  // 30: thoughts.UserService.GetFollowers:output_type -> thoughts.Users
	8,  // 31: thoughts.UserService.FollowUser:output_type -> thoughts.Empty
	8,  // 32: thoughts.UserService.UnfollowUser:output_type -> thoughts.Empty
	11, // 33: thoughts.AuthService.CreateSession:output_type -> thoughts.Session
	11, // 34: thoughts.AuthService.GetSession:output_type -> thoughts.Session
	8,  // 35: thoughts.AuthService.DeleteSession:output_type -> thoughts.Empty
	12, // 36: thoughts.AuthService.GetSessions:output_type -> thoughts.Sessions
	1,  // 37: thoughts.PostService.CreatePost:output_type -> thoughts.Identifier
	17, // 38: thoughts.PostService.GetFeed:output_type -> thoughts.Posts
	17, // 39: thoughts.PostService.GetPosts:output_type -> thoughts.Posts
	17, // 40: thoughts.PostService.GetLikedPosts:output_type -> thoughts.Posts
	15, // 41: thoughts.PostService.GetPost:output_type -> thoughts.Post
	8,  // 42: thoughts.PostService.DeletePost:output_type -> thoughts.Empty
	8,  // 43: thoughts.PostService.LikePost:output_type -> thoughts.Empty
	8,  // 44: thoughts.PostService.UnlikePost:output_type -> thoughts.Empty
	8,  // 45: thoughts.PostService.RepostPost:output_type -> thoughts.Empty
	8,  // 46: thoughts.PostService.RemoveRepost:output_type -> thoughts.Empty
	25, // [25:47] is the sub-list for method output_type
	3,  // [3:25] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_pb_thoughts_proto_init() }
func file_pb_thoughts_proto_init() {
	if File_pb_thoughts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_thoughts_proto_rawDesc), len(file_pb_thoughts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_pb_thoughts_proto_goTypes,
		DependencyIndexes: file_pb_thoughts_proto_depIdxs,
		MessageInfos:      file_pb_thoughts_proto_msgTypes,
	}.Build()
	File_pb_thoughts_proto = out.File
	file_pb_thoughts_proto_goTypes = nil
	file_pb_thoughts_proto_depIdxs = nil
}
